### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MattSkala** [smartlook/smartlook-android-sdk#44] opened 2020-04-13 09:29 UTC
We observed the following crash after updating the SDK. In only appeared once so far.

Stack trace:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.smartlook.sdk.smartlook.analytics.d.b(d.java:216)
       at com.smartlook.sdk.smartlook.analytics.c.i(c.java:209)
       at com.smartlook.sdk.smartlook.analytics.c.b.b.c(b.java:224)
       at com.smartlook.sdk.smartlook.analytics.c.b.b.c(b.java:37)
       at com.smartlook.sdk.smartlook.analytics.c.b.b$m.run(b.java:195)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

SDK version: 1.4.0-native

OS: Android 10

**Comment by SenNeonoveNoci** [comment] 2020-04-16 15:18
Hi @MattSkala,

we identified the cause of the problem and its gonna be fixed in next release.

**Closed as completed by SenNeonoveNoci** 2020-04-16 15:18 UTC
Labels: bug
